### ISSUE TITLE
Is possible get the device token id?

### ISSUE THREAD

**Issue by Jairolaya12x** [kiwi-bop/openpay#2]
Hi,

I'm developing a app with openpay, but the backend need that i send the device token id, the plugin allows get this?

Thanks, and great work 🤘

**Comment by cesarureno** [comment]
Any update for this feature

**Comment by Jairolaya12x** [comment]
@cesarureno I created my own plugin because this plugins don't have all features, yet is under development but works fine 
https://github.com/Jairolaya12x/openpay_plugin
King regards
